export const ENV_CONFIG = Object.freeze({
    APP: {
        JSON_PLACEHOLDER_BASE_URL: process.env.NEXT_PUBLIC_JSON_PLACEHOLDER_BASE_URL,
        GOOGLE_GENERATIVE_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_GENERATIVE_AI_API_KEY
    }
})